name: ubuntu-release-info
summary: Ubuntu distribution release information
description: |
    Similar to the 'distro-info' package, this class parses and
    contains the Ubuntu release information. Instead of a static data
    file, this instead downloads the the meta-release information from
    changelogs.ubuntu.com, and parses it to determine the most recent
    release information.

base: core18
grade: stable
confinement: strict
adopt-info: ubuntu-release-info
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

apps:
    ubuntu-release-info:
        command: bin/ubuntu-release-info
        plugs:
            - network

parts:
    ubuntu-release-info:
        plugin: python
        source: https://github.com/powersj/ubuntu-release-info
        source-type: git
        override-pull: |
            snapcraftctl pull
            DATE="$(date +%Y.%m.%d)"
            GIT="$(git rev-parse --short HEAD)"
            snapcraftctl set-version "${DATE}+git${GIT}"
